/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#FCF9FA",
        "surface-container-low": "#FFF2F5",
        "on-background": "#3A2E31",
        "tertiary-fixed": "#ffffff",
        "secondary-dim": "#A38038",
        "surface-container-highest": "#E8D3D8",
        "on-primary-fixed": "#4D1B28",
        "on-primary": "#ffffff",
        "surface-tint": "#D9728B",
        "outline": "#CCA8AF",
        "primary": "#D9728B",
        "on-secondary-fixed-variant": "#927429",
        "inverse-primary": "#F7CAD3",
        "on-primary-container": "#662638",
        "error-dim": "#791903",
        "tertiary": "#8A797D",
        "on-surface-variant": "#7A686C",
        "surface-container-high": "#F5E6E9",
        "outline-variant": "#EADBE0",
        "secondary-container": "#FDE6BA",
        "secondary-fixed-dim": "#D6BB7A",
        "on-tertiary": "#ffffff",
        "error-container": "#fd795a",
        "on-secondary-container": "#4A3A13",
        "secondary": "#C5A059",
        "surface-dim": "#EFE6E8",
        "on-secondary": "#ffffff",
        "primary-dim": "#B8576E",
        "background": "#FCF9FA",
        "tertiary-container": "#ffffff",
        "on-primary-fixed-variant": "#80354A",
        "tertiary-dim": "#706165",
        "inverse-on-surface": "#F2F2F2",
        "surface-container": "#FAECEF",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#3A2E31",
        "secondary-fixed": "#FDE6BA",
        "on-tertiary-container": "#332C2E",
        "primary-fixed": "#F7CAD3",
        "on-error-container": "#6e1400",
        "primary-container": "#FADBE2",
        "tertiary-fixed-dim": "#F4F0EB",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#EAA8B7",
        "surface-bright": "#ffffff",
        "on-tertiary-fixed-variant": "#6f6d69",
        "inverse-surface": "#241A1D",
        "on-tertiary-fixed": "#51504d",
        "surface-variant": "#F5E6E9",
        "on-secondary-fixed": "#2B2109",
        "error": "#a73b21"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
