/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf9f6",
        "surface-container-low": "#f4f4f0",
        "on-background": "#303330",
        "tertiary-fixed": "#ffffff",
        "secondary-dim": "#395765",
        "surface-container-highest": "#e1e3de",
        "on-primary-fixed": "#401517",
        "on-primary": "#fff7f6",
        "surface-tint": "#884f50",
        "outline": "#797b78",
        "primary": "#884f50",
        "on-secondary-fixed-variant": "#41606e",
        "inverse-primary": "#f0a9a9",
        "on-primary-container": "#5a2a2b",
        "error-dim": "#791903",
        "tertiary": "#605f5b",
        "on-surface-variant": "#5d605c",
        "surface-container-high": "#e7e9e4",
        "outline-variant": "#b0b3ae",
        "secondary-container": "#c7e7f8",
        "secondary-fixed-dim": "#b9d9ea",
        "on-tertiary": "#fcf8f3",
        "error-container": "#fd795a",
        "on-secondary-container": "#375663",
        "secondary": "#456371",
        "surface-dim": "#d9dbd6",
        "on-secondary": "#f2faff",
        "primary-dim": "#7a4445",
        "background": "#faf9f6",
        "tertiary-container": "#ffffff",
        "on-primary-fixed-variant": "#653334",
        "tertiary-dim": "#54534f",
        "inverse-on-surface": "#9d9d9a",
        "surface-container": "#eeeeea",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#303330",
        "secondary-fixed": "#c7e7f8",
        "on-tertiary-container": "#64625e",
        "primary-fixed": "#f0a9a9",
        "on-error-container": "#6e1400",
        "primary-container": "#f0a9a9",
        "tertiary-fixed-dim": "#f4f0eb",
        "on-error": "#fff7f6",
        "primary-fixed-dim": "#e19c9c",
        "surface-bright": "#faf9f6",
        "on-tertiary-fixed-variant": "#6f6d69",
        "inverse-surface": "#0d0f0d",
        "on-tertiary-fixed": "#51504d",
        "surface-variant": "#e1e3de",
        "on-secondary-fixed": "#244350",
        "error": "#a73b21"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
